---
title: Software 
description: Install Software
privilege: TrustedInstaller 
actions:

  # Utilities - 7-Zip, Visual C++ Runtimes, DirectX
  - !status: {status: 'Installing Software'}
  - !powerShell:
      command: '.\SOFTWARE.ps1'
      exeDir: true
      wait: true
      weight: 150
      runas: currentUserElevated
      oobe: true

  # SynToolkit
  - !status: {status: 'Installing SynToolkit'}
  - !powerShell:
      command: '.\SOFTWARE.ps1 -SynToolkit'
      exeDir: true
      wait: true
      weight: 100
      runas: currentUserElevated
      oobe: true

  # macOS cursors
  - !status: {status: 'Applying macOS cursors', option: 'macos-look'}
  - !powerShell:
      command: '.\SOFTWARE.ps1 -MacCursors'
      exeDir: true
      wait: true
      weight: 20
      option: 'macos-look'
      runas: currentUserElevated
      oobe: true

  # Browsers
  - !status: {status: 'Installing Brave', option: 'browser-brave'}
  - !powerShell:
      command: '.\SOFTWARE.ps1 -Brave'
      exeDir: true
      wait: true
      weight: 120
      option: 'browser-brave'
      runas: currentUserElevated
      oobe: true

  - !status: {status: 'Installing Firefox', option: 'browser-firefox'}
  - !powerShell:
      command: '.\SOFTWARE.ps1 -Firefox'
      exeDir: true
      wait: true
      weight: 120
      option: 'browser-firefox'
      runas: currentUserElevated
      oobe: true

  - !status: {status: 'Installing Chrome', option: 'browser-chrome'}
  - !powerShell:
      command: '.\SOFTWARE.ps1 -Chrome'
      exeDir: true
      wait: true
      weight: 120
      option: 'browser-chrome'
      runas: currentUserElevated
      oobe: true

  - !status: {status: 'Installing .NET 8 Desktop Runtime'}
  - !download: {url: 'https://aka.ms/dotnet/8.0/windowsdesktop-runtime-win-x64.exe', destination: '%temp%\dotnet8_desktop_x64.exe', overwrite: true}
  - !download: {url: 'https://aka.ms/dotnet/8.0/windowsdesktop-runtime-win-x86.exe', destination: '%temp%\dotnet8_desktop_x86.exe', overwrite: true}
  - !cmd: {command: '"%temp%\dotnet8_desktop_x64.exe" /install /quiet /norestart', runas: currentUserElevated, wait: true}
  - !cmd: {command: '"%temp%\dotnet8_desktop_x86.exe" /install /quiet /norestart', runas: currentUserElevated, wait: true}